apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app: my-nginx-app
spec:
  containers:
  - name: nginx
    image: 471112683049.dkr.ecr.us-east-1.amazonaws.com/cal-com:latest
    ports:
    - containerPort: 80
