# Use the Nginx image from your ECR Public repository as the base image
FROM 471112683049.dkr.ecr.us-east-1.amazonaws.com/based-image-call:latest

# Copy the index.html to the default Nginx public directory
COPY web-frontend/index.html /usr/share/nginx/html/index.html
